version: '3'

services:
  mtproto-proxy:
    image: telegrammessenger/proxy
    env_file: .env
    ports:
      - "1337:443"
    volumes:
      - proxy-config:/data
    restart: "no"
    networks:
      - tg-proxy

volumes:
  proxy-config:

networks: 
  tg-proxy: