version: '3'

services:
  mtproto-proxy:
    image: telegrammessenger/proxy
    env_file: .env
    ports:
      - "1337:443"
    volumes:
      - proxy-config:/data
    restart: always
    networks:
      - tg-proxy
  
  ss5:
    image: dijedodol/simple-socks5-server:latest
    ports:
      - '2101:1080'
    env_file: .env
    restart: always
    networks:
      - tg-proxy

volumes:
  proxy-config:

networks: 
  tg-proxy:
